/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as Organization from "../generated-artifacts/Organization.json";
import * as OrganizationInterface from "../generated-artifacts/OrganizationInterface.json";
import * as Organized from "../generated-artifacts/Organized.json";
export const artifacts = {
  Organized: Organized as ContractArtifact,
  Organization: Organization as ContractArtifact,
  OrganizationInterface: OrganizationInterface as ContractArtifact
};
